name: Pipeline

on:
  push:
    branches: [main]
    paths: ["package.json", "src/**"]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths: ["package.json", "src/**"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  check:
    name: Type Checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/node

      - name: Run the type checker
        run: pnpm check

  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/node

      - name: Run the linter
        run: pnpm lint

  build:
    name: Building
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/node

      - name: Build the package
        run: pnpm build

  test:
    name: Testing
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/node

      - name: Run tests
        run: pnpm test

  process:
    name: Processing Changesets
    needs: [test]
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.changesets.outputs.published }}
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/node

      - name: Process changesets
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run release:version
          publish: pnpm run release:publish
          title: "Pending Releases"
          commit: "Update changelog and release"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PULL_REQUEST_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: |
          echo "published=${{ steps.changesets.outputs.published }}" >> $GITHUB_OUTPUT

  snapshot:
    name: Releasing Snapshot
    needs: [process]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.process.outputs.published == 'false' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/node

      - name: Publish snapshot version
        run: |
          pnpm run release:snapshot:version
          pnpm run release:snapshot:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true
